---
title: "Good Jobs Lab Fellow- Assessment"
author: "Sam Fraley"
date: "4/30/2023"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidycensus)
library(tigris)
library(readxl)
library(tmap)
library(sf)
library(DT)
library(gt)
```

<font size = "4.5"> Read in the raw data </font>

```{r readin}
setwd("C:\\Users\\sfraley\\Downloads\\PCV")

areas <- readxl::read_excel("Zip Codes_Rural and Urban_Reference.xlsx", sheet =2,
                  col_types = c("text","numeric","numeric","numeric","numeric","numeric")) %>%
  rename("Zip" = `Zip Code`)

wage <- readxl::read_excel("Employee Wage and Zip Code Data.xlsx", sheet =1,
                            col_types = c("text","numeric","text","text")) %>%
  rename("Zip" = `Zip Code of Residence`)

```

 $-$
 $-$
 $-$
 $-$
 

<font size = "4.5"> Create a "rural.flag" variable, for zip codes that have over 50% rural population.
Join zip code characteristics to wage data. </font> 
```{r flag}
areas <- areas %>%
  mutate(rural.flag = ifelse(`% Rural` > 0.5, 1,0))

join <- wage %>%
  left_join(areas, by = c("Zip" = "Zip")) %>%
  mutate(count = 1) %>%
  na.omit()

```
 $-$
 $-$
 $-$
 $-$
 <b> <center> <font size="6"> "join" data table</font> </center> </b>
```{r print areas, echo = F}
DT::datatable(join,
         #extensions = c('FixedColumns',"FixedHeader"),
          options = list(scrollX = TRUE, 
                         scrollY = TRUE,
                         paging=T,
                         fixedHeader=FALSE,
                         rowWidth='10%'))
```