---
title: "Seasonality Index"
author: "Sam Fraley"
date: "4/27/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


In this project, we use two seasonal adjustment packages in R to calculate seasonally-adjusted employment data by industry in Philadelphia. We followed methods from a research brief published by researchers at Florida Gulf Coast University's Regional Economic Insititute: <https://www.fgcu.edu/cob/reri/news/reports/issue-brief-fgcu-seasonality-index>.



```{r seasonal}
library(tidyverse)
library(car)
library(blsAPI)
library(tidycensus)
library(lubridate)
library(janitor)
library(scales)
library(gt)
library(stringr)
library(fuzzyjoin)
library(tabulizer)
library(zoo)
library(timetk)
library(seasonal)
library(forecast)
library(broom)
library(sweep)
library(seasthedata)
setwd("A:\\Research and Special Reporting\\Seasonality Index")

  
  #https://anomaly.io/seasonal-trend-decomposition-in-r/index.html
  
  payload <- list(
    'seriesid'=c('SMU42979610000000001', #Nonfarm Employment
                 'SMU42979611500000001', #Mining, Logging, and Construction
                 'SMU42979613000000001', #Manufacturing
                 'SMU42979614100000001', #Wholesale Trade
                 'SMU42979614200000001', #Retail Trade
                 'SMU42979614300000001', #Transportation and Utilities
                 'SMU42979615000000001', #Information
                 'SMU42979615500000001', #Finance and Insurance
                 'SMU42979616000000001', #Professional and Businees Services
                 'SMU42979616500000001', #Education and Health Services
                 'SMU42979617000000001'  #Leisure and Hospitality
    ), 
    'startyear'=2015,
    'endyear'=2030, 
    'registrationKey' = '160c8d9a0e7c40bcada565263a877b85')
  
  ces.employment <- blsAPI(payload, api_version = 2, return_data_frame = T) %>%
    mutate(Industry = case_when(seriesID ==  'SMU42979610000000001' ~ "Nonfarm Employment",
                                seriesID == 'SMU42979611500000001' ~ "Mining, Logging, and Construction",
                                seriesID == 'SMU42979613000000001' ~ "Manufacturing",
                                seriesID == 'SMU42979614100000001' ~ "Wholesale Trade",
                                seriesID == 'SMU42979614200000001' ~ "Retail Trade",
                                seriesID == 'SMU42979614300000001' ~ "Transportation and Utilities",
                                seriesID == 'SMU42979615000000001' ~ "Information",
                                seriesID == 'SMU42979615500000001' ~ "Finance and Insurance",
                                seriesID == 'SMU42979616000000001' ~ "Professional and Business Services",
                                seriesID == 'SMU42979616500000001' ~ "Education and Health Services",
                                seriesID == 'SMU42979617000000001'  ~ "Leisure and Hospitality"),
           Employment = as.numeric(value) * 1000) %>%
    mutate(Month = my(paste(periodName, year, sep = " "))) 
  
  
  ces.wide <- ces.employment %>%
    pivot_wider(names_from = Industry, values_from = Employment) 
  
  ces.wide[is.na(ces.wide)] <- 0
  
  ces.wide <- ces.wide %>%
    group_by(Month) %>%
    summarize_if(is.numeric, sum)
  
  ces.map <- ces.employment %>%
    group_by(Industry) %>%
    tidyr::nest() %>%
    mutate(data.ts = map(data, function(x) {
      tem2 <- ts(x$Employment, frequency = 12, start = c(2016, 1))
      tem3 <- seas(tem2)
      as.data.frame(tem3$data) %>%
        mutate(month = x$Month)
    })) 

  ces.test <- ces.employment %>%
    select(Industry, Month, Employment) %>%
    group_by(Industry)
  
  industry <- as.data.frame(unique(ces.employment$Industry))
  ###junk #####

  
group.ts <- seasthedata(ces.test)%>%
  mutate(join = paste0(Industry,Month))

ces.employment.join <- ces.employment %>%
  mutate(join = paste0(Industry, Month))

ts.join.w <- group.ts %>%
  left_join(ces.employment.join, by = c("join"))%>%
  select("Industry" = Industry.x, "Month" = Month.x, "Seasonally Adjusted" = Employment.x, "Non-Seasonally Adjusted" = Employment.y) %>%
  mutate(Industry = ifelse(Industry == "Nonfarm Employment", "Total Non-Farm", Industry))

ts.join <- ts.join.w %>%
  pivot_longer(!c(Month, Industry), names_to = "measure", values_to = "Total Employment") 


#plotting####
industries <- ts.join.w %>%
  distinct(Industry)

ind.list <- (industries$Industry) 

for (i in ind.list) {
  name <- i
  
  industry <- ts.join%>%
    subset(Industry == i) 
  
  temp.plot <- industry %>%
    ggplot(aes(x = Month, y= `Total Employment`, group=measure, color = measure)) +
    geom_line(size = 1.1) +
  ggtitle(paste("Philadelpia", i, "\n Employment", sep =" ")) +
       theme_minimal() +
    theme(legend.position="top", legend.title=element_blank(), 
          axis.text.x = element_text(size=11, color="black"), 
          axis.title.y = element_text(face="bold", size = 11, color="black"),
          axis.text.y = element_text(size=11, color="black"),
          legend.text = element_text(size=11, color="black", face="bold"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          plot.title =  element_text(size = 18, colour = "black", face = "bold", hjust = 0.5)) 
  
  
  
plot(temp.plot)
  
}

```

```{r Find Seasonality Table}

industry.table <- ts.join %>%
  pivot_wider(names_from = measure, values_from = `Total Employment`) %>%
  mutate(difference = abs((`Non-Seasonally Adjusted` - `Seasonally Adjusted`)/`Seasonally Adjusted`)) %>%
  group_by(Industry) %>%
  summarize_if(is.numeric, mean)

```
